# pull official base image
FROM node:13.12.0-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install
# RUN npm install react-scripts@3.4.1 -g --silent

# add app
COPY . ./

ENV REACT_APP_DEPLOYMENT_HOST=http://20.103.59.235:8080

RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build usr/share/nginx/html
EXPOSE 80

# start app
CMD ["nginx", "-g", "daemon off;"]